name: Test

on:
  pull_request:

  push:
    branches:
      - develop
      - 'feature/**'

  workflow_call:

  workflow_dispatch:

jobs:
  test:
    name: Run test suite for ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Test Bash script
        shell: bash
        run: |
          rm -rf .uv .uv-version
          ./uv --version

      - name: Test DosBatch script
        shell: cmd
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          rd .uv /q /s
          rd .uv-version /q /s
          .\uv.bat --version
